EXEC NALUNO (2020121705);

--EX 3:
3.
SELECT AUTORES.NOME
FROM AUTORES
MINUS SELECT AUTORES.NOME
FROM AUTORES ,LIVROS
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR AND TO_CHAR(DATA_EDICAO,'YYYY') <> TO_CHAR(SYSDATE,'YYYY') ;

EXEC SQLCHECK('FHMBJNSCNGSTKQA'); 

--EX 4:
4.
SELECT AUTORES.NOME , ''||count(LIVROS.CODIGO_LIVRO) as "Num. Livros"
FROM AUTORES, LIVROS
WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR
GROUP BY AUTORES.NOME
UNION
SELECT NOME, 'nenhum'
FROM AUTORES
MINUS
SELECT NOME, 'nenhum'
FROM AUTORES, LIVROS
where AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR
ORDER BY 1;

EXEC SQLCHECK('FHUERGLECXADMUQ'); 

--EX 5:
5.
SELECT AUTORES.NOME, REPLACE(COUNT(LIVROS.CODIGO_LIVRO),0,'Nenhum') AS "Num. Livros"
FROM AUTORES
LEFT OUTER JOIN LIVROS
ON  AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR
GROUP BY AUTORES.NOME
ORDER BY AUTORES.NOME;

EXEC SQLCHECK('FHSCCDRDZKARLUB'); 

--EX 6:
6.
SELECT TO_CHAR(DATA_EDICAO,'YYYY') as "ANO", count(CODIGO_LIVRO) as "Num. Livros"
FROM LIVROS
GROUP BY TO_CHAR(DATA_EDICAO,'YYYY')
ORDER BY 1;

EXEC SQLCHECK('FHRDLEUFARMVNAI');

--EX 7:
7.
SELECT AUTORES.NOME
FROM LIVROS,AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR AND LIVROS.DATA_EDICAO > '2012-12-31'
GROUP BY AUTORES.NOME
HAVING count(LIVROS.CODIGO_LIVRO) > 1
ORDER BY NOME;

EXEC SQLCHECK('FHHDTLNGYXLNOMV'); 

--EX 8:
8.
SELECT TO_CHAR(DATA_VENDA,'YYYY') as "ANO",sum(QUANTIDADE) as "Quantidade Vendida"
FROM VENDAS
GROUP BY TO_CHAR(DATA_VENDA,'YYYY')
ORDER BY 1;

EXEC SQLCHECK('FHKJQVJHDPJOPWL'); 

--EX 9:
SELECT GENERO, TO_CHAR(DATA_VENDA,'MM/YYYY') as "MES", SUM(QUANTIDADE) as "Quant. Vendida"
FROM LIVROS,VENDAS
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO AND TO_CHAR(DATA_VENDA,'YYYY') = '2014'
GROUP BY GENERO, TO_CHAR(DATA_VENDA,'MM/YYYY')
HAVING SUM(QUANTIDADE) > 25 
ORDER BY SUM(QUANTIDADE) DESC;

EXEC SQLCHECK('FHTVUUFIEHCVQZQ'); 

--EX 10:
10.
SELECT 1 + TRUNC(months_between (data_venda, data_edicao)/12) as "ANO" , SUM(QUANTIDADE) as "Quantidade Vendida"
FROM LIVROS,VENDAS,CLIENTES
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO AND VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE AND MORADA like '%Lisboa%' AND months_between (data_venda, data_edicao) < 60
GROUP BY TRUNC(months_between (data_venda, data_edicao)/12)
HAVING SUM(QUANTIDADE) > 16
ORDER BY 1;

EXEC SQLCHECK('FHZIFAIJVEPCRDQ'); 

--11
11.
SELECT SUBSTR(MORADA,(INSTR(MORADA,' ',-1)+1))as "CIDADE", SUM(QUANTIDADE) as "Quant.Vendida"
FROM VENDAS,CLIENTES
WHERE VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE
GROUP BY SUBSTR(MORADA,(INSTR(MORADA,' ',-1)+1))
ORDER BY SUM(QUANTIDADE) DESC;

EXEC SQLCHECK('FHMTQJZKYSXZSCF'); 







