EXEC NALUNO (2020121705);

--Ex 3:

SELECT CODIGO_LIVRO, TITULO
FROM LIVROS
WHERE GENERO = 'Informática';

exec sqlcheck ('FBUHOJDECAQQSOP');

--Ex 4:
4.
SELECT TITULO 
FROM LIVROS 
WHERE GENERO = 'Policial' AND PAGINAS > 500;

exec sqlcheck ('FBNUMEJFNWJUCVE');

--Ex 5:
5.
SELECT DISTINCT GENERO 
FROM LIVROS 
WHERE PRECO_TABELA > 45 OR PAGINAS > 700;

exec sqlcheck ('FBTGJMYGMKLHLKA');

--Ex 6:
6.
SELECT TITULO 
FROM LIVROS 
WHERE GENERO = 'Informática' ORDER BY PRECO_TABELA DESC; 

exec sqlcheck ('FBVEMIAHEOADHXS');

--Ex 7:
7.
SELECT ISBN, TITULO, PRECO_TABELA, QUANT_EM_STOCK 
FROM LIVROS
WHERE GENERO = 'Informática' ORDER BY PRECO_TABELA DESC, QUANT_EM_STOCK ASC; 

exec sqlcheck ('FBISGKRIZEJXNSS');

--Ex 8:
8.
SELECT DISTINCT CODIGO_AUTOR
FROM LIVROS
WHERE QUANT_EM_STOCK > 0;

exec sqlcheck ('FBGNPWPJDHXSRNZ');

--Ex 9:
9.
SELECT TITULO 
FROM LIVROS 
WHERE GENERO != 'Policial'; 

exec sqlcheck ('FBDIESEKOVUTTPV');

--Ex 10:

10.
SELECT TITULO
FROM LIVROS
WHERE GENERO NOT IN 'Policial';

exec sqlcheck ('FBWEIAULEXHNAVX');

--Ex 11:

11.
SELECT NOME
FROM AUTORES
WHERE IDADE > 30 and GENERO_PREFERIDO = 'Policial' 
ORDER BY Nome ASC;

exec sqlcheck ('FBEDRFJMAPTCRPM');

--Ex 12

12.
SELECT NOME 
FROM AUTORES
WHERE NOME LIKE '%r%' AND NOME LIKE '%d%';

exec sqlcheck ('FBKQIWUNTYJCWHY');

--Ex 13

13.
SELECT TITULO 
FROM LIVROS
WHERE TITULO LIKE 'O%' and TITULO LIKE '%st%' OR  TITULO LIKE 'M%' AND TITULO LIKE '%to%';

exec sqlcheck ('FBNEADXOMTHUZXY');

--Ex 14

14.
SELECT TITULO
FROM LIVROS
WHERE GENERO = 'Policial' or GENERO = 'Romance' or Genero = 'Aventura'; 

exec sqlcheck ('FBOQJEGPTMCGVNA');

--Ex 15

15.
SELECT 'O livro "'|| TITULO || '" custa ' || PRECO_TABELA || ' euros.' AS "Listagem de Livros"
FROM LIVROS;

exec sqlcheck ('FBLPLJHQYFXONHJ');