EXEC NALUNO (2020121705);

--Ex 3:

3.
SELECT TITULO
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR and LIVROS.GENERO = 'Policial' and AUTORES.NOME = 'Cláudio Tereso';

EXEC SQLCHECK('FCRJGVRAWCUQDMT');

-- Ex 4:

4.
SELECT TITULO
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR and LIVROS.GENERO = 'Policial' and AUTORES.MORADA like '%Coimbra%';

EXEC SQLCHECK('FCTFWGYBRRDOETR');

-- Ex 5:

5.
SELECT DISTINCT AUTORES.NOME
FROM AUTORES , LIVROS
WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR AND AUTORES.GENERO_PREFERIDO = LIVROS.GENERO;

EXEC SQLCHECK('FCNXSFBCZEMFTOL');

-- Ex 6:

6.
SELECT TITULO , PRECO_TABELA 
FROM LIVROS ,VENDAS, CLIENTES
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO AND VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE AND CLIENTES.MORADA like '%Coimbra%';

EXEC SQLCHECK('FCZBYENDWGNMCZJ');

-- Ex 7:

7.
SELECT AUTORES.NOME 
FROM AUTORES, CLIENTES
WHERE AUTORES.N_CONTRIBUINTE = CLIENTES.N_CONTRIBUINTE;

EXEC SQLCHECK('FCFREDCEKEEXMEQ');

-- Ex 8:

8.
SELECT AUTORES.NOME, LIVROS.TITULO, LIVROS.GENERO
FROM AUTORES,LIVROS
WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR AND AUTORES.GENERO_PREFERIDO != LIVROS.GENERO
ORDER BY AUTORES.NOME ASC;

EXEC SQLCHECK('FCLMFDUFYTDWYAC');

-- Ex 9:

9.
SELECT LIVROS.TITULO, (livros.unidades_vendidas * livros.PRECO_TABELA*0.3) as "Rendeu"
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR;

EXEC SQLCHECK('FCZQAYZGYAYXJBI');

-- Ex 10:

10.
SELECT TITULO, (livros.unidades_vendidas * livros.PRECO_TABELA*0.3) as "Rendimento"
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR and (livros.unidades_vendidas * livros.PRECO_TABELA*0.3) > 10000
ORDER BY LIVROS.GENERO , LIVROS.PRECO_TABELA ;

EXEC SQLCHECK('FCLLLIVHUDLXGJG');

-- Ex 11:

11.
SELECT TITULO, ROUND (LIVROS.PRECO_TABELA/LIVROS.PAGINAS , 2 ) as "Custo página", CEIL(LIVROS.PRECO_TABELA/LIVROS.PAGINAS) as "Custo pág.(sup)",FLOOR(LIVROS.PRECO_TABELA/LIVROS.PAGINAS) as "Custo pág.(inf)" 
FROM LIVROS
WHERE LIVROS.PAGINAS >= 400 AND LIVROS.PAGINAS <= 700
ORDER BY round((LIVROS.PRECO_TABELA/LIVROS.PAGINAS), 2) ASC;

EXEC SQLCHECK('FCIOICFIWPKKPDU');

-- Ex 12

12.
SELECT upper(titulo) as "Titulo (em maiúsculas)", lower(titulo) as "Titulo (em minúsculas)", initcap(titulo) as "Titulo (1ª  letra maiúscula)"
FROM LIVROS;

EXEC SQLCHECK('FCDEAPRJKRNHXWY');

-- Ex 13

13.
SELECT TITULO as "Titulo"
FROM LIVROS
WHERE GENERO like 'informática';

EXEC SQLCHECK('FCVLAQFKHBCPVUT');

-- Ex 14

14.

SELECT NOME as "Nome completo", SUBSTR(NOME, 1, INSTR(NOME, ' ')-1) as "Primeiro Nome", SUBSTR(NOME,(INSTR(NOME,' ',-1)+1)) as "Ultimo Nome"
FROM AUTORES;

EXEC SQLCHECK('FCEVDVALSQWNMME');

--Ex 15

15.

SELECT DISTINCT upper(TITULO) as "Titulo (em maisculas)", lower(LIVROS.GENERO) as "genero (min.)", AUTORES.NOME as "Nome Autor (1a letra)"
FROM LIVROS, AUTORES, EDITORAS 
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR AND LIVROS.CODIGO_EDITORA = EDITORAS.CODIGO_EDITORA AND EDITORAS.NOME='FCA - EDITORA'
Order BY AUTORES.NOME, "Titulo (em maisculas)" DESC;

EXEC SQLCHECK('FCBRVTIMKAXSXAQ');

--Ex 16

16.

SELECT TITULO from LIVROS 
WHERE length(TITULO) > 20;

EXEC SQLCHECK('FCKOECUNNUHUSEY');

--Ex 17

17.

SELECT TITULO, PRECO_TABELA as PRECO, round(PRECO_TABELA*0.1355 + PRECO_TABELA,1) AS "PRECO_COM_AUMENTO"
FROM LIVROS
WHERE GENERO='Policial';

EXEC SQLCHECK('FCFTFBNOWLIPTJN');





