EXEC NALUNO (2020121705);

--EX 3:
3.
SELECT TITULO
FROM LIVROS
WHERE TO_CHAR(DATA_EDICAO,'yyyy') = '2011';

EXEC SQLCHECK('FDUIIRTAKWEXEMS');

--EX 4:
4.

SELECT TO_CHAR(SYSDATE,'HH24:MI:SS AM') AS "Hora Actual", TO_CHAR(SYSDATE,'DD, Month, YYYY') AS "Data Actual"
FROM DUAL;

EXEC SQLCHECK('FDWNLITBBLANFKS');

--EX 5:
5.
SELECT TITULO AS "Titulo", PRECO_TABELA AS "Preço"
FROM LIVROS
WHERE sysdate - DATA_EDICAO < 3000;

EXEC SQLCHECK('FDCAWZTCVLWYGAP');

--EX 6:
6.
SELECT DISTINCT TITULO
FROM LIVROS,VENDAS,CLIENTES
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO AND VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE AND CLIENTES.MORADA like '%Lisboa%' AND TO_CHAR(DATA_VENDA,'mm-yyyy') = '02-2014'
ORDER BY LIVROS.TITULO;

EXEC SQLCHECK('FDVHQSPDEEBFHIW');

--EX 7:
7.
SELECT DISTINCT TITULO 
FROM LIVROS,VENDAS
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO AND GENERO = 'Informática' AND TO_CHAR(DATA_EDICAO,'MM-YYYY') = TO_CHAR(DATA_VENDA,'MM-YYYY')
ORDER by TITULO;

EXEC SQLCHECK('FDRRBNZEHNWOISK');

--EX 8:
8.
SELECT AUTORES.NOME 
FROM AUTORES,LIVROS
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR AND GENERO = 'Informática' AND LIVROS.PAGINAS > 190 AND LIVROS.DATA_EDICAO BETWEEN '2013-06-21' AND '2013-09-22';

EXEC SQLCHECK('FDYHZMQFGKWTJJM');

--EX 9:
9.
SELECT TITULO as "Titulo", TO_CHAR(DATA_EDICAO,'YYYY-MM-DD HH24:MI:SS') as DATA_EDICAO, TRUNC((SYSDATE - DATA_EDICAO)/365.242199,0) AS "Num. de anos"
FROM LIVROS
WHERE GENERO = 'Informática'
ORDER BY TITULO;

EXEC SQLCHECK('FDLODEOGLOGAKUD');

--EX 10
10.
SELECT CLIENTES.NOME
FROM CLIENTES,VENDAS,LIVROS
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO AND VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE AND GENERO = 'Informática' 
AND TO_CHAR(DATA_VENDA, 'HH24') < 17 AND TO_CHAR(DATA_VENDA, 'D') = 4 AND TO_CHAR(DATA_VENDA, 'W') = 1;

EXEC SQLCHECK('FDCYRYZHRTDHLVG');

--EX 11
11.
SELECT AUTORES.NOME
FROM AUTORES
MINUS SELECT AUTORES.NOME
FROM AUTORES,LIVROS
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR;

EXEC SQLCHECK('FDLBDDBIQETTMFB');

--EX 12
12.
SELECT AUTORES.NOME
FROM AUTORES
MINUS SELECT AUTORES.NOME
FROM AUTORES,LIVROS
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR AND TO_CHAR(DATA_EDICAO,'YYYY') != '2014';

EXEC SQLCHECK('FDMBAEUJCCTONSE');





